# Generated by Django 4.2.1 on 2023-06-20 23:56

import auction.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.IntegerField(default=1687305415)),
                ('start_time', models.IntegerField(default=1687305415)),
                ('sale_token_num', models.IntegerField(default=1)),
                ('minimum_value_per_token', models.IntegerField(default=1)),
                ('contract_address', models.CharField(default='', max_length=100)),
                ('state', models.IntegerField(choices=[(auction.models.AuctionState['Waiting'], 0), (auction.models.AuctionState['InProgress'], 1), (auction.models.AuctionState['Canceled'], 2), (auction.models.AuctionState['Finished'], 3)], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_token', models.IntegerField()),
                ('total_value', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=500)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
            ],
        ),
        migrations.CreateModel(
            name='LikedAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('user', models.ForeignKey(on_delete=models.Model, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_num', models.IntegerField(default=0)),
                ('total_val', models.BigIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
