# Generated by Django 4.2.1 on 2023-06-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('encrypted_private_key', models.CharField(max_length=600)),
                ('eth_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=500)),
                ('symbol', models.CharField(max_length=8)),
                ('balance', models.BigIntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.cryptowallet')),
            ],
        ),
    ]
