# Generated by Django 4.2.1 on 2023-06-20 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=400, verbose_name='لینک وبسایت')),
                ('telegram_id', models.CharField(max_length=400, verbose_name='آیدی تلگرام ')),
                ('details', models.CharField(max_length=400, verbose_name='توضیحات پروژه')),
                ('github_id', models.CharField(max_length=400, verbose_name=' آیدی گیتهاب')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTokenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6, verbose_name='نماد')),
                ('total_supply', models.BigIntegerField(default=0)),
                ('development_stage', models.IntegerField(choices=[(project.models.DevelopmentStages['Inception'], 0), (project.models.DevelopmentStages['Elaboration'], 1), (project.models.DevelopmentStages['Deployment'], 2), (project.models.DevelopmentStages['Canceled'], 3)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام پروژه')),
                ('contract_address', models.CharField(max_length=400, verbose_name='آدرس کانترکت پروژه')),
                ('image', models.CharField(max_length=400, verbose_name='عکس')),
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.projectbasicinfo')),
                ('token_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.projecttokeninfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
